# Generated by Django 6.0.5 on 2026-05-25 19:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationHopital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_usd_en_cdf', models.DecimalField(decimal_places=2, default=Decimal('2500.00'), max_digits=10)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du Taux',
            },
        ),
    ]
