# Generated by Django 6.0.5 on 2026-05-27 01:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_role_fonction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('categorie', models.CharField(choices=[('ADM', 'Administratif'), ('LABO', 'Laboratoire'), ('SOIN', 'Soins'), ('ECHO', 'Échographie'), ('RADIO', 'Radiologie')], max_length=10, verbose_name='Catégorie')),
                ('prix', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix (USD)')),
                ('valeur_normale', models.CharField(blank=True, help_text='Ex: 70-110 mg/dl, Négatif, etc. Utilisé uniquement pour le Laboratoire.', max_length=150, null=True, verbose_name='Valeur Normale / Référence (Labo uniquement)')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(editable=False, max_length=20, unique=True)),
                ('noms', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('age', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('fiche_payee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_crees', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='app.service')),
            ],
        ),
    ]
