# Generated by Django 6.0.5 on 2026-06-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hopital'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonction',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hopital_fonction', to='app.hopital'),
        ),
    ]
