# Generated by Django 6.0.5 on 2026-05-28 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prestation_service_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigneVital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension_sys', models.IntegerField()),
                ('tension_dia', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frequence_cardiaque', models.IntegerField()),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
