# Generated by Django 6.0.5 on 2026-07-01 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_prestation_hopital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_hopital', to='app.hopital'),
        ),
    ]
