# Generated by Django 6.0.5 on 2026-05-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patient_options_facture_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='USD', max_length=3),
        ),
    ]
