# Generated by Django 6.0.5 on 2026-07-03 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_patient_hopital'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiement_hopital', to='app.hopital'),
        ),
    ]
