# Generated by Django 6.0.5 on 2026-07-03 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_paiement_hopital'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrationkardex',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='blocoperatoire',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='chambre',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='clientexterne',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='compterenduaccouchement',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='consultationmaternite',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='deces',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='demandeexamen',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='demandeexamenexterne',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='depense',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='examenexterneresultat',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='ficheaccouchement',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='interventionmaintenance',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='kardex',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='lignemedicament',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='lit',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='lotpharmacie',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='maternite',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='medicament',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='ordonnanceexterne',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='ordonnanceitem',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='ordonnancesortie',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='orientation',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='produitpharmacie',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='sessionsoins',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='signevital',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='soinoccasionnel',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='sortiepharmacie',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='suiviquotidien',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
        migrations.AddField(
            model_name='typechambre',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
    ]
