# Generated by Django 6.0.5 on 2026-07-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_administrationkardex_hopital_blocoperatoire_hopital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='clientEx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.clientexterne'),
        ),
    ]
