# Generated by Django 6.0.5 on 2026-07-09 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_videoroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_video_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
