# Generated by Django 6.0.5 on 2026-07-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_videoroom_allowed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='antecedent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
