# Generated by Django 6.0.5 on 2026-07-15 21:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_consultation_antecedent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportJournalierPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rapport', models.DateField(default=django.utils.timezone.localdate)),
                ('type_rapport', models.CharField(choices=[('personnel', 'Rapport du personnel'), ('service', 'Rapport de service'), ('direction', 'Rapport de direction')], default='personnel', max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('nombre_personnel_present', models.PositiveIntegerField(default=0)),
                ('nombre_personnel_absent', models.PositiveIntegerField(default=0)),
                ('incidents_signales', models.PositiveIntegerField(default=0)),
                ('recommandations', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_rediges', to=settings.AUTH_USER_MODEL)),
                ('hopital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_journaliers', to='app.hopital')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_journaliers', to='app.service')),
            ],
            options={
                'verbose_name': 'Rapport journalier du personnel',
                'verbose_name_plural': 'Rapports journaliers du personnel',
                'ordering': ['-date_rapport', '-date_creation'],
            },
        ),
    ]
