# Generated by Django 6.0.5 on 2026-07-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rapportjournalierpersonnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapportjournalierpersonnel',
            name='date_rapport',
            field=models.DateField(auto_now_add=True),
        ),
    ]
