# Generated by Django 6.0.5 on 2026-07-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_rapportjournalierpersonnel_date_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
