# Generated by Django 6.0.5 on 2026-07-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_medicament_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='devise',
            field=models.CharField(choices=[('CDF', 'CDF'), ('USD', 'USD')], default='CDF', max_length=3),
        ),
    ]
