# Generated by Django 6.0.5 on 2026-07-24 05:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_paiement_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnostic_final',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix (CDF)'),
        ),
    ]
