# Generated by Django 6.0.5 on 2026-07-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_consultation_diagnostic_final_alter_prestation_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
