# Generated by Django 6.0.5 on 2026-07-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_ordonnance_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitpharmacie',
            name='devise',
            field=models.CharField(choices=[('USD', 'USD'), ('CDF', 'CDF')], default='CDF', max_length=3),
        ),
    ]
