# Generated by Django 6.0.5 on 2026-07-29 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_produitpharmacie_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexamenexterne',
            name='total_cdf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='clientEx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.clientexterne'),
        ),
    ]
