# Generated by Django 6.0.5 on 2026-08-01 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_demandeexamenexterne_total_cdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signevital',
            name='hopital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital'),
        ),
    ]
