# Generated by Django 6.0.5 on 2026-08-03 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_signevital_hopital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suivi', models.DateTimeField(auto_now_add=True)),
                ('diagnostic_du_jour', models.TextField(blank=True, null=True, verbose_name='Diagnostic du jour')),
                ('evolution', models.TextField(blank=True, null=True, verbose_name='Évolution clinique')),
                ('consignes', models.TextField(blank=True, null=True, verbose_name='Consignes / Prescriptions particulières')),
                ('hopital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.hopital')),
                ('hospitalisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_medecin', to='app.hospitalisation')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suivi Médecin',
                'verbose_name_plural': 'Suivis Médecin',
                'ordering': ['-date_suivi'],
            },
        ),
    ]
