# Generated by Django 6.0.5 on 2026-08-03 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_suivimedecin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisMedecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_avis', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic / Synthèse'), ('EVOLUTION', 'Évolution clinique'), ('COMMENTAIRE', 'Commentaire / Note'), ('CONSEIL', 'Conseil / Recommandation'), ('AUTRE', 'Autre')], default='COMMENTAIRE', max_length=20, verbose_name="Type d'avis")),
                ('titre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Titre (optionnel)')),
                ('contenu', models.TextField(verbose_name='Point de vue / commentaire')),
                ('date_avis', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'avis")),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_medecin', to='app.consultation', verbose_name='Consultation (optionnel)')),
                ('hopital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_medecin', to='app.hopital', verbose_name='Hôpital')),
                ('hospitalisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_medecin', to='app.hospitalisation', verbose_name='Hospitalisation (optionnel)')),
                ('medecin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_medecin_donnes', to=settings.AUTH_USER_MODEL, verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_medecin', to='app.patient', verbose_name='Patient')),
            ],
            options={
                'verbose_name': 'Avis médecin',
                'verbose_name_plural': 'Avis médecins',
                'ordering': ['-date_avis'],
                'indexes': [models.Index(fields=['patient', '-date_avis'], name='app_avismed_patient_3f761c_idx')],
            },
        ),
    ]
