# Generated by Django 6.0.5 on 2026-08-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_avismedecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='statut_p',
            field=models.CharField(blank=True, choices=[('N', 'nouveau/nouvelle'), ('A', 'ancien/ancienne')], default='A', max_length=20, null=True),
        ),
    ]
