# Generated by Django 6.0.5 on 2026-08-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_patient_statut_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='motif',
            field=models.CharField(max_length=50, verbose_name='Motif'),
        ),
    ]
