# Generated by Django 6.0.5 on 2026-08-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_depense_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexamenexterne',
            name='medecin_demandeur',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
