# Generated by Django 6.0.5 on 2026-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_demandeexamenexterne_medecin_demandeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeexamenexterne',
            name='but',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandeexamenexterne',
            name='clinique',
            field=models.TextField(blank=True, null=True),
        ),
    ]
