# Generated by Django 6.0.5 on 2026-08-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_demandeexamenexterne_but_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='montant_hopital',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text="Montant pour l'hôpital (calculé automatiquement)", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_medecin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Montant pour le médecin (calculé automatiquement)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='pourcentage_medecin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Pourcentage pour le médecin référent (ex: 10.00 pour 10%)', max_digits=5, null=True),
        ),
    ]
