# Generated by Django 6.0.5 on 2026-08-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_paiement_montant_hopital_paiement_montant_medecin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignemedicament',
            name='quantite',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
