# Generated by Django 6.0.5 on 2026-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_lignemedicament_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignemedicament',
            name='duree',
            field=models.CharField(help_text='Exemple : 5 jours', max_length=100),
        ),
        migrations.AlterField(
            model_name='lignemedicament',
            name='motif_arret',
            field=models.TextField(blank=True, help_text='Pourquoi le médecin a changé ou arrêté ce médicament', null=True),
        ),
        migrations.AlterField(
            model_name='lignemedicament',
            name='posologie',
            field=models.CharField(help_text='Exemple : 1 comprimé, 3 fois par jour', max_length=200),
        ),
        migrations.AlterField(
            model_name='lignemedicament',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
