# Generated by Django 6.0.5 on 2026-09-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_lignemedicament_duree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitpharmacie',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
