# Generated by Django 6.0.5 on 2026-09-25 05:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_produitpharmacie_actif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins'), ('MATERNITE', 'Maternité'), ('DECES', 'Actes de décès'), ('EXAMENS', 'Examens'), ('CHIRURGIE', 'Chirurgie'), ('CARTE_FIDELITE', 'Achat Carte de Fidélité'), ('PHARMACIE', 'Pharmacie'), ('EXAMEN_EXTERNE', 'Examen Externe'), ('ENTREPRISE', 'Paiement Entreprise'), ('HOSPITALISATION', 'Hospitalisation'), ('ACTE_MEDICAL', 'Acte médical')], max_length=20),
        ),
        migrations.CreateModel(
            name='ActeMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_patient', models.CharField(choices=[('INTERNE', 'Patient interne'), ('EXTERNE', 'Client externe')], max_length=10)),
                ('date_acte', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('montant_prevu', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observation', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client_externe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actes_medicaux', to='app.clientexterne')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_medicaux_crees', to=settings.AUTH_USER_MODEL)),
                ('hopital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_medicaux', to='app.hopital')),
                ('medecin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_medicaux_realises', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actes_medicaux', to='app.patient')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actes_medicaux', to='app.prestation')),
            ],
        ),
        migrations.AddField(
            model_name='paiement',
            name='acte_medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='app.actemedical', verbose_name='Acte médical'),
        ),
    ]
