# Generated by Django 6.0.5 on 2026-09-26 16:03

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_paiement_service_actemedical_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actemedical',
            options={'ordering': ['-date_acte', '-date_creation'], 'verbose_name': 'Acte médical', 'verbose_name_plural': 'Actes médicaux'},
        ),
        migrations.RemoveField(
            model_name='actemedical',
            name='prestation',
        ),
        migrations.AddField(
            model_name='actemedical',
            name='prestations',
            field=models.ManyToManyField(related_name='actes_medicaux', to='app.prestation', verbose_name='Prestations'),
        ),
        migrations.AlterField(
            model_name='actemedical',
            name='client_externe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actes_medicaux', to='app.clientexterne', verbose_name='Client externe'),
        ),
        migrations.AlterField(
            model_name='actemedical',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_medicaux_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='actemedical',
            name='date_acte',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'acte"),
        ),
        migrations.AlterField(
            model_name='actemedical',
            name='hopital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_medicaux', to='app.hopital', verbose_name='Hôpital'),
        ),
        migrations.AlterField(
            model_name='actemedical',
            name='medecin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actes_medicaux_realises', to=settings.AUTH_USER_MODEL, verbose_name='Médecin'),
        ),
        migrations.AlterField(
            model_name='actemedical',
            name='montant_prevu',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant total prévu'),
        ),
        migrations.AlterField(
            model_name='actemedical',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='actemedical',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actes_medicaux', to='app.patient', verbose_name='Patient interne'),
        ),
        migrations.AlterField(
            model_name='actemedical',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='actemedical',
            name='type_patient',
            field=models.CharField(choices=[('INTERNE', 'Patient interne'), ('EXTERNE', 'Client externe')], max_length=10, verbose_name='Type de personne'),
        ),
    ]
