# Generated by Django 6.0.5 on 2026-09-30 04:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_actemedical_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(blank=True, max_length=150, verbose_name="Nom d'utilisateur")),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('ECHEC_CONNEXION', 'Échec de connexion')], db_index=True, max_length=20)),
                ('modele', models.CharField(blank=True, db_index=True, max_length=60, verbose_name="Type d'objet")),
                ('objet_id', models.CharField(blank=True, max_length=40)),
                ('objet_repr', models.CharField(blank=True, max_length=200, verbose_name='Objet concerné')),
                ('changements', models.JSONField(blank=True, default=dict)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('chemin', models.CharField(blank=True, max_length=255, verbose_name='Page utilisée')),
                ('date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('hopital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='app.hopital', verbose_name='Hôpital')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-date', '-id'],
            },
        ),
    ]
