# Generated by Django 6.0.5 on 2026-09-30 18:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpsMorgue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_personne', models.CharField(choices=[('INTERNE', 'Patient interne'), ('EXTERNE', 'Client externe')], max_length=10)),
                ('date_entree', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_sortie', models.DateTimeField(blank=True, null=True)),
                ('est_sorti', models.BooleanField(default=False)),
                ('prix_par_jour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('client_externe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corps_morgue', to='app.clientexterne')),
                ('hopital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corps_morgue', to='app.hopital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corps_morgue', to='app.patient')),
            ],
        ),
    ]
