# Generated by Django 6.0.5 on 2026-10-09 06:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_corpsmorgue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='montant_verse_cdf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant versé converti (CDF)'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='prix_campagne_cdf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix de la campagne (CDF)'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='clientEx',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='app.clientexterne'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='service',
            field=models.CharField(choices=[('FICHE', 'Fiche'), ('CONSULTATION', 'Consultation'), ('LABO', 'Labo'), ('ECHOGRAPHIE', 'Échographie'), ('RADIO', 'Radiographie'), ('SOIN', 'Soins'), ('MATERNITE', 'Maternité'), ('DECES', 'Actes de décès'), ('EXAMENS', 'Examens'), ('CHIRURGIE', 'Chirurgie'), ('CARTE_FIDELITE', 'Achat Carte de Fidélité'), ('PHARMACIE', 'Pharmacie'), ('EXAMEN_EXTERNE', 'Examen Externe'), ('ENTREPRISE', 'Paiement Entreprise'), ('HOSPITALISATION', 'Hospitalisation'), ('ACTE_MEDICAL', 'Acte médical'), ('CAMPAGNE', 'Campagne médicale')], max_length=20),
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type_campagne', models.CharField(choices=[('GRATUITE', 'Campagne gratuite'), ('PAYANTE', 'Campagne payante'), ('COUPLE', 'Campagne couple payante'), ('COUPLE_GRATUIT', 'Campagne couple gratuite')], default='GRATUITE', max_length=20, verbose_name='Type de campagne')),
                ('prix_defaut_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix par défaut (CDF)')),
                ('date_debut', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ACTIVE', 'Active'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=15)),
                ('active', models.BooleanField(default=True, verbose_name='Campagne active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('creee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_creees', to=settings.AUTH_USER_MODEL)),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes', to='app.hopital', verbose_name='Hôpital')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='paiement',
            name='campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='app.campagne', verbose_name='Campagne'),
        ),
        migrations.CreateModel(
            name='CampagneParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_personnes', models.PositiveIntegerField(default=1, help_text='1 personne ou 2 personnes pour une campagne couple.', verbose_name='Nombre de personnes')),
                ('prix_total_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Prix total à payer (CDF)')),
                ('montant_paye_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant déjà payé (CDF)')),
                ('reste_a_payer_cdf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Reste à payer (CDF)')),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='INSCRIT', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='app.campagne', verbose_name='Campagne')),
                ('clientEx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations_campagnes', to='app.clientexterne', verbose_name='Client externe')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_participants_crees', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participations_campagnes', to='app.patient', verbose_name='Patient interne')),
            ],
            options={
                'verbose_name': 'Participant à une campagne',
                'verbose_name_plural': 'Participants aux campagnes',
                'ordering': ['-date_inscription'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('patient__isnull', False)), fields=('campagne', 'patient'), name='unique_patient_par_campagne'), models.UniqueConstraint(condition=models.Q(('clientEx__isnull', False)), fields=('campagne', 'clientEx'), name='unique_client_externe_par_campagne')],
            },
        ),
    ]
